### Add flashcard
POST {{base_url}}/flashcard/add
Content-Type: application/json

{
  "userId": {
    "value": "asdfa"
  },
  "original": {
    "text": "cat",
    "context": "This is my cat."
  },
  "translation": {
    "text": "kot",
    "context": "To jest mój kot."
  },
  "deckId": {
    "value": "talia"
  }
}

### Add flashcard
POST {{base_url}}/flashcard/add
Content-Type: application/json

{
  "userId": {
    "value": "asdfa"
  },
  "original": {
    "text": "dog",
    "context": "This is my dog."
  },
  "translation": {
    "text": "pies",
    "context": "To jest mój pies."
  },
  "deckId": {
    "value": "talia"
  }
}

### show next flashcard
POST {{base_url}}/flashcard/next
Content-Type: application/json

{
  "value": "asdfa"
}


### answer
POST {{base_url}}/flashcard/answer
Content-Type: application/json

{
  "flashcardId": "1",
  "translation": "pies",
  "confidence": "EXCELENT"
}

### show next flashcard
POST {{base_url}}/flashcard/listDeck
Content-Type: application/json

{
  "value": "talia"
}